#!/usr/bin/env python3
"""Scan Python test files statically and report audit candidates as JSON.

This covers what linters do not. Run ruff for the rest, for example:
    uvx ruff check --select F811,F631,B011,B015,B017,PGH005,PT --statistics TESTS

Checks, each reported with a count and a few examples:
  no-assertion          tests with no assert, pytest.raises, assert* call, or asserting helper
  tautology             asserts that cannot fail (truthy constants, non-empty tuple, list, set, or dict literals)
  self-comparison       assert x == x: a tautology for built-in values, but possibly a test of a custom __eq__
  assert-in-except      asserts only in an except block, so the test passes when nothing is raised
  unreachable-assert    asserts after a return or raise in the same block
  shadowed-test         a test name defined twice in one scope, so only the last one runs
  exact-duplicate-body  tests in one file with identical bodies and different names (often a copy never edited)
  cross-file-duplicate-body  identical bodies in different files (weaker: imports and fixtures may differ)
  literal-only-body     tests whose bodies differ only in literals (parametrize candidates)
  uncollectable-class   test classes with __init__ (own, inherited, or generated by dataclass or attrs)
  module-disabled       modules that set __test__ = False, so none of their tests run
  disabled-class        classes with __test__ = False that no scanned class inherits from
  in-norecursedirs      test functions under directories that an explicit norecursedirs excludes
  yield-in-test, returns-value, empty-parametrize, assert-only-in-loop, assert-true-two-args, imported-test
                        tests that never run, run twice, or cannot fail
  mock-typo             .called_once_with() and similar, which check nothing (Python 3.12+ raises instead)
  weak-assertions       tests that end on an assertion, and whose every assertion checks only that a
                        result exists: is not None, hasattr, len(x) > 0, assertIsNotNone
  xfail-never-runs      xfail(run=False): the body never runs
  misnamed-test         misspelt test names (tset_, tst_, ...), and methods with asserts whose names miss the test pattern
  bare-skip-decorator   @skip or @unittest.skip without a reason, which replaces the class or test with a
                        function, so its tests never run and never show as skipped
  file-not-collected    files with test functions whose names do not match the runner's file pattern
  not-run-by-runner     with --runner unittest: module-level test functions and non-TestCase classes, which never run
  not-collected         tests defined in the code but absent from --nodeids
  skip-unconditional, xfail-not-strict, skip-inside-test   unconditional skips, pytest xfail markers
                        without strict, and unconditional skip() calls; conditional skips are only counted
  autouse-fixtures      autouse fixtures, their scope, and roughly how many tests they reach
  unused-fixtures       fixtures never requested by name (approximate; confirm with pytest-deadfixtures)
  unread-fixture        tests that request a fixture that returns a value, and never read it: its setup
                        is paid for its side effects only, or for nothing
  risk-*                sleeps, real clocks, unseeded randomness, network, subprocess, threads, env, and
                        global state: `global` statements, writes to the test module's module-level
                        containers, and attributes of imported modules set without monkeypatch
  transactional-tests   Django TransactionTestCase or LiveServerTestCase (also through project base
                        classes), django_db(transaction=True), django_db(True), reset_sequences=True,
                        pytestmark, and the transactional_db, live_server, and django_db_reset_sequences
                        fixtures, including fixtures that request them
  mock-density          tests with five or more patches
  parametrize-size      parametrize matrices of 50 or more cases, including stacked decorators
  hypothesis-settings   @settings on property tests (max_examples, deadline, suppressed health checks),
                        and settings.register_profile and load_profile calls
  pbt-candidates        tests that call both halves of a round trip, such as dumps and loads, or
                        encode_order and decode_order

Usage:
    static_scan.py [PATH ...] [--config DIR] [--runner pytest|unittest] [--nodeids FILE]
                   [--blame] [--examples N] [--json-out FILE]
    static_scan.py diff BEFORE_JSON AFTER_JSON [--json-out FILE]

`diff` is the tamper check for any change to the suite, including your own:
it lists removed tests (matching moved or renamed ones by body), new skips and
xfails, tests with fewer assertions or with checks weakened to truthiness or
"is not None", changed discovery settings, and addopts that run fewer tests or
hide failures. It exits with 1 when it finds any of these. It cannot see
product code that special-cases tests (grep for PYTEST_CURRENT_TEST), coverage
thresholds, or pragma: no cover.

Run it from the pytest rootdir, so paths match node IDs. PATH defaults to the
configured testpaths, or the current directory. pytest's python_files,
python_classes, python_functions, testpaths, norecursedirs, and xfail_strict
are read from pyproject.toml, pytest.ini, tox.ini, or setup.cfg in --config.
With --runner unittest (Django's runner, `python -m unittest`), discovery
follows unittest's rules instead: files matching test*.py, TestCase
subclasses, and methods starting with "test".

For --nodeids, use `pytest --collect-only -q` without -m or -k, so deselected
tests still count as collected.

Counts are static estimates. Inherited test methods, custom collectors, and
parametrisation make them differ from the collected count, so never report a
static count as the number of tests.

Run it with the project's own Python when you can: a file that uses syntax
newer than the interpreter is listed under parse_errors, not scanned.

Standard library only; runs on Python 3.8+.
"""
from __future__ import annotations

import argparse
import ast
import configparser
import copy
import datetime as _dt
import fnmatch
import hashlib
import json
import os
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

DEFAULT_FILES = ["test_*.py", "*_test.py"]
DEFAULT_CLASSES = ["Test"]
DEFAULT_FUNCTIONS = ["test"]
DEFAULT_NORECURSE = ["*.egg", ".*", "_darcs", "build", "CVS", "dist", "node_modules", "venv", "{arch}"]
ALWAYS_SKIP_DIRS = {"__pycache__", ".git", ".hg", ".tox", ".nox", ".venv", "venv", "site-packages", "node_modules", ".mypy_cache", ".pytest_cache", ".ruff_cache"}

ASSERT_HELPER_RE = re.compile(r"^_*(assert|check|verify|expect)", re.IGNORECASE)
RAISES_WARNS_RE = re.compile(r"(^|_)(raises|warns|deprecated_call)(_|$)", re.IGNORECASE)
SKIP_CALLS = {"skip", "skipTest", "importorskip", "xfail"}
MOCK_ASSERT_RE = re.compile(r"^assert_(called|not_called|any_call|has_calls|awaited|not_awaited)")
FAIL_CALLS = {"fail", "failIf", "failUnless", "failUnlessEqual", "failIfEqual"}
ASSERT_CONTEXTS = {
    "raises", "warns", "deprecated_call", "assertRaises", "assertRaisesRegex", "assertWarns", "assertWarnsRegex",
    "assertLogs", "assertNoLogs", "assertNumQueries", "django_assert_num_queries", "django_assert_max_num_queries",
}
# Fixture names that plugins request themselves, so tests never name them.
PLUGIN_FIXTURES = {
    "django_db_setup", "django_db_modify_db_settings", "django_db_modify_db_settings_parallel_suffix",
    "django_db_use_migrations", "django_db_keepdb", "django_db_createdb", "django_db_serialized_rollback",
    "django_test_environment", "celery_config", "celery_includes", "celery_parameters", "celery_worker_parameters",
    "celery_enable_logging", "celery_worker_pool", "anyio_backend", "event_loop_policy", "event_loop",
    "vcr_config", "vcr_cassette_dir", "default_cassette_name", "record_mode", "faker_seed", "faker_locale",
    "hypothesis_profile", "base_url", "browser_context_args", "browser_type_launch_args", "pytestconfig",
}
ROUND_TRIP_PAIRS = [
    ("dumps", "loads"), ("dump", "load"), ("encode", "decode"), ("serialize", "deserialize"),
    ("serialise", "deserialise"), ("to_json", "from_json"), ("to_dict", "from_dict"), ("pack", "unpack"),
    ("compress", "decompress"), ("encrypt", "decrypt"), ("marshal", "unmarshal"), ("parse", "format"),
    ("parse", "render"), ("parse", "unparse"), ("quote", "unquote"),
]
# Verbs whose names mark the two halves of a round trip inside snake_case names: encode_order and
# decode_order, to_json and from_json. A name with "to" in it also pairs with its sides swapped:
# order_to_json and json_to_order.
ROUND_TRIP_VERBS = {
    "dumps": "loads", "dump": "load", "encode": "decode", "serialize": "deserialize", "serialise": "deserialise",
    "pack": "unpack", "compress": "decompress", "encrypt": "decrypt", "marshal": "unmarshal", "quote": "unquote",
    "escape": "unescape", "to": "from", "encrypted": "decrypted", "encoded": "decoded",
}
ROUND_TRIP_VERBS.update({b: a for a, b in list(ROUND_TRIP_VERBS.items())})
CONTAINER_CALLS = {"dict", "list", "set", "defaultdict", "OrderedDict", "Counter", "deque"}
MUTATING_METHODS = {"append", "extend", "insert", "update", "add", "setdefault", "pop", "popitem", "remove", "discard", "clear", "appendleft"}
RISK_CALLS = {
    "risk-sleep": {"time.sleep", "sleep", "asyncio.sleep", "gevent.sleep", "trio.sleep", "anyio.sleep"},
    "risk-clock": {"datetime.now", "datetime.utcnow", "datetime.today", "date.today", "time.time", "timezone.now"},
    "risk-random": {"random.random", "random.randint", "random.randrange", "random.choice", "random.shuffle", "random.sample", "random.uniform", "uuid.uuid4", "uuid4"},
    "risk-network": {
        "requests.get", "requests.post", "requests.put", "requests.delete", "requests.patch", "requests.head", "requests.request",
        "httpx.get", "httpx.post", "httpx.put", "httpx.delete", "httpx.request", "urllib.request.urlopen", "urlopen",
        "socket.socket", "socket.create_connection", "smtplib.SMTP", "ftplib.FTP", "http.client.HTTPConnection", "http.client.HTTPSConnection",
    },
    "risk-subprocess": {"subprocess.run", "subprocess.Popen", "subprocess.call", "subprocess.check_call", "subprocess.check_output", "os.system", "os.popen"},
    "risk-thread": {"threading.Thread", "Thread", "multiprocessing.Process", "concurrent.futures.ThreadPoolExecutor", "ThreadPoolExecutor", "ProcessPoolExecutor"},
    "risk-chdir": {"os.chdir"},
}
FREEZE_NAMES = {"freeze_time", "freezegun", "time_machine", "travel", "freezer", "frozen_time", "time_travel"}
TRANSACTIONAL_BASES = {"TransactionTestCase", "LiveServerTestCase", "StaticLiveServerTestCase", "ChannelsLiveServerTestCase"}
# pytest-django fixtures that make a test transactional: each one flushes the database afterwards.
TRANSACTIONAL_FIXTURES = {"transactional_db", "live_server", "django_db_reset_sequences"}


# --------------------------------------------------------------------------- config


CONFIG_KEYS = (
    "python_files", "python_classes", "python_functions", "testpaths", "norecursedirs", "xfail_strict", "strict_xfail", "strict",
    "addopts", "filterwarnings", "markers",
)
# pytest 9's search order; a TOML or ini file counts only when it has a pytest section.
CONFIG_FILES = (
    ("pytest.toml", "toml", ("pytest",)),
    (".pytest.toml", "toml", ("pytest",)),
    ("pytest.ini", "ini", "pytest"),
    (".pytest.ini", "ini", "pytest"),
    ("pyproject.toml", "toml", ("tool", "pytest")),
    ("tox.ini", "ini", "pytest"),
    ("setup.cfg", "ini", "tool:pytest"),
)


def read_toml_section(path: Path, where: tuple[str, ...]) -> dict | None:
    text = path.read_text(errors="replace")
    try:
        import tomllib  # Python 3.11+

        node = tomllib.loads(text)
        for key in where:
            node = node.get(key) if isinstance(node, dict) else None
        if not isinstance(node, dict):
            return None
        if isinstance(node.get("ini_options"), dict):
            # pyproject.toml: [tool.pytest] (pytest 9) and [tool.pytest.ini_options] both count.
            node = {**node["ini_options"], **{k: v for k, v in node.items() if k != "ini_options"}}
        return node
    except Exception:
        headers = ["pytest"] if where == ("pytest",) else ["tool.pytest", "tool.pytest.ini_options"]
        section: dict | None = None
        for header in headers:
            m = re.search(rf"^\[{re.escape(header)}\]\s*$(.*?)(?=^\[|\Z)", text, re.M | re.S)
            if not m:
                continue
            section = section or {}
            for key in CONFIG_KEYS:
                km = re.search(rf"^{key}\s*=\s*(\[.*?\]|\".*?\"|'.*?'|\S+)", m.group(1), re.M | re.S)
                if km:
                    raw = km.group(1)
                    section[key] = re.findall(r"[\"']([^\"']+)[\"']", raw) if raw.startswith("[") else raw.strip("\"'")
        return section


def read_pytest_config(config_dir: Path) -> dict:
    """Read the pytest keys the scan needs from the first configuration file, in pytest 9's order."""
    for name, kind, where in CONFIG_FILES:
        path = config_dir / name
        if not path.is_file():
            continue
        if kind == "toml":
            section = read_toml_section(path, where)  # type: ignore[arg-type]
            if section is None:
                continue
            return normalise_config({k: section[k] for k in CONFIG_KEYS if k in section}, str(path))
        parser = configparser.ConfigParser(interpolation=None)
        try:
            parser.read(path)
        except configparser.Error:
            continue
        if parser.has_section(where):  # type: ignore[arg-type]
            return normalise_config({k: parser.get(where, k) for k in CONFIG_KEYS if parser.has_option(where, k)}, str(path))  # type: ignore[arg-type]
    return normalise_config({}, None)


def normalise_config(raw: dict, source: str | None) -> dict:
    def as_list(value, default):
        if value is None:
            return list(default)
        if isinstance(value, str):
            return value.split()
        return [str(v) for v in value]

    def truthy(value) -> bool:
        return value is True or str(value).lower() in ("true", "1", "yes")

    strict = any(truthy(raw.get(k)) for k in ("xfail_strict", "strict_xfail", "strict") if raw.get(k) is not None)
    return {
        "source": source,
        "python_files": as_list(raw.get("python_files"), DEFAULT_FILES),
        "python_classes": as_list(raw.get("python_classes"), DEFAULT_CLASSES),
        "python_functions": as_list(raw.get("python_functions"), DEFAULT_FUNCTIONS),
        "testpaths": as_list(raw.get("testpaths"), []),
        "norecursedirs": as_list(raw.get("norecursedirs"), DEFAULT_NORECURSE),
        "xfail_strict": strict,
        "addopts": as_list(raw.get("addopts"), []),
        "filterwarnings": as_list(raw.get("filterwarnings"), []) if not isinstance(raw.get("filterwarnings"), str) else raw["filterwarnings"].splitlines(),
    }


def glob_match(name: str, patterns: list[str]) -> bool:
    return any(fnmatch.fnmatch(name, p) for p in patterns)


def name_match(name: str, patterns: list[str]) -> bool:
    """pytest's rule: patterns with glob characters are globs, others are prefixes."""
    for pattern in patterns:
        if any(c in pattern for c in "*?["):
            if fnmatch.fnmatch(name, pattern):
                return True
        elif name.startswith(pattern):
            return True
    return False


# --------------------------------------------------------------------------- AST helpers


def dotted(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        base = dotted(node.value)
        return f"{base}.{node.attr}" if base else node.attr
    if isinstance(node, ast.Call):
        return dotted(node.func)
    return ""


def last_name(node: ast.AST) -> str:
    return dotted(node).rsplit(".", 1)[-1]


def source_of(node: ast.AST, limit: int = 100) -> str:
    """Source text of a node (Python 3.9+), cut to `limit` characters."""
    text = ast.unparse(node) if hasattr(ast, "unparse") else (dotted(node) or type(node).__name__)
    return text if len(text) <= limit else text[: limit - 1] + "…"


def is_docstring(stmt: ast.stmt) -> bool:
    return isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant) and isinstance(stmt.value.value, str)


def walk_body(func) -> list[ast.AST]:
    """All nodes in a function body, excluding its decorators and signature."""
    nodes = []
    for stmt in func.body:
        nodes.extend(ast.walk(stmt))
    return nodes


def walk_own(func) -> list[ast.AST]:
    """Nodes in a function's own body, without nested functions, lambdas, or classes."""
    nested = (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda, ast.ClassDef)
    out, stack = [], [s for s in func.body if not isinstance(s, nested)]
    while stack:
        node = stack.pop()
        out.append(node)
        for child in ast.iter_child_nodes(node):
            if not isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda, ast.ClassDef)):
                stack.append(child)
    return out


DATACLASS_DECORATORS = {"dataclass", "define", "frozen", "mutable", "s", "attrs"}
# Decorators that register a function as a callback, so a test_ name does not make it a test.
REGISTRATION_RE = re.compile(r"(register|receiver|hook|\.route|\.task|\.command|\.connect|listener|subscriber)", re.IGNORECASE)
MOCK_TYPOS = {"called_once_with", "called_with", "called_once", "has_calls", "not_called", "any_call", "awaited_once_with", "awaited_with", "not_awaited"}
LIFECYCLE_METHODS = {"setUp", "tearDown", "setUpClass", "tearDownClass", "setup_method", "teardown_method", "setup_class", "teardown_class", "setup", "teardown", "asyncSetUp", "asyncTearDown"}
WEAK_ASSERT_METHODS = {"assertTrue", "assertFalse", "assertIsNotNone", "assertIsInstance", "assert_", "assertIsNone"}
MISNAMED_TEST_RE = re.compile(r"^(tset|tst|tets|ttest|testt|tesst|tes|est|teest)_\w+")


def non_empty_literal(node: ast.AST, known: set[str]) -> bool:
    """True when an iterable cannot be empty: a non-empty literal, a name bound to one, or range() of constants."""
    if isinstance(node, (ast.List, ast.Tuple, ast.Set)):
        return bool(node.elts)
    if isinstance(node, ast.Dict):
        return bool(node.keys)
    if isinstance(node, ast.Name):
        return node.id in known
    if isinstance(node, ast.Call):
        name = last_name(node.func)
        if name in ("enumerate", "zip", "sorted", "reversed", "list", "tuple", "set", "product", "permutations", "combinations") and node.args:
            return all(non_empty_literal(a, known) for a in node.args)
        if name == "range" and node.args:
            values = [v for v in (int_constant(a) for a in node.args) if v is not None]
            return len(values) == len(node.args) and len(range(*values[:3])) > 0
    return False


def int_constant(node: ast.AST) -> int | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, int):
        return node.value
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        inner = int_constant(node.operand)
        return -inner if inner is not None else None
    return None


def container_names(nodes) -> set[str]:
    """Module-level names bound to a mutable container: {}, [], set(), dict(), defaultdict(list), and similar."""
    names: set[str] = set()
    for node in nodes:
        value = node.value if isinstance(node, (ast.Assign, ast.AnnAssign)) else None
        targets = node.targets if isinstance(node, ast.Assign) else [node.target] if isinstance(node, ast.AnnAssign) else []
        if isinstance(value, (ast.Dict, ast.List, ast.Set)) or (isinstance(value, ast.Call) and last_name(value.func) in CONTAINER_CALLS):
            names.update(t.id for t in targets if isinstance(t, ast.Name))
    return names


def returns_value(func) -> bool:
    """True when a fixture returns or yields something other than None."""
    for node in walk_own(func):
        if isinstance(node, (ast.Return, ast.Yield)) and node.value is not None:
            if not (isinstance(node.value, ast.Constant) and node.value.value is None):
                return True
    return False


def round_trip_partner(name: str, called: set[str]) -> str | None:
    """A called name that undoes `name`: encode_x for decode_x, from_json for to_json, y_to_x for x_to_y."""
    parts = name.split("_")
    for i, part in enumerate(parts):
        partner = ROUND_TRIP_VERBS.get(part)
        if partner:
            candidate = "_".join(parts[:i] + [partner] + parts[i + 1:])
            if candidate != name and candidate in called:
                return candidate
    if "to" in parts[1:-1]:
        i = parts.index("to", 1)
        swapped = "_".join(parts[i + 1:] + ["to"] + parts[:i])
        if swapped != name and swapped in called:
            return swapped
    return None


def literal_names(nodes) -> set[str]:
    names: set[str] = set()
    for node in nodes:
        if isinstance(node, ast.Assign) and non_empty_literal(node.value, names):
            names.update(t.id for t in node.targets if isinstance(t, ast.Name))
    return names


def is_fixture(func) -> bool:
    return any(dotted(d).endswith("fixture") for d in func.decorator_list)


def fixture_args(func) -> dict:
    for d in func.decorator_list:
        if isinstance(d, ast.Call) and dotted(d.func).endswith("fixture"):
            return {kw.arg: kw.value.value for kw in d.keywords if kw.arg in ("scope", "autouse", "name") and isinstance(kw.value, ast.Constant)}
    return {}


def call_matches(name: str, targets: set[str]) -> bool:
    return name in targets or any(name.endswith("." + t) for t in targets if "." in t)


class LiteralStripper(ast.NodeTransformer):
    def visit_Constant(self, node: ast.Constant):
        if isinstance(node.value, bool) or node.value is None:
            return node
        return ast.copy_location(ast.Constant(value="<lit>"), node)


def body_fingerprint(func, strip_literals: bool) -> str | None:
    body = [s for i, s in enumerate(func.body) if not (i == 0 and is_docstring(s))]
    if len(body) < 2:
        return None
    body = [copy.deepcopy(s) for s in body]
    if strip_literals:
        body = [LiteralStripper().visit(s) for s in body]
    dumped = "\n".join(ast.dump(s, annotate_fields=False, include_attributes=False) for s in body)
    if not strip_literals:
        # Identical bodies with different parameters or parametrisation test different inputs.
        signature = [ast.dump(func.args, annotate_fields=False, include_attributes=False)]
        signature += [ast.dump(d, annotate_fields=False, include_attributes=False) for d in func.decorator_list]
        dumped += "\n" + "\n".join(signature)
    return hashlib.sha1(dumped.encode()).hexdigest()


def is_skip_call(node: ast.Call) -> bool:
    name = dotted(node.func)
    return last_name(node.func) in SKIP_CALLS and (name in SKIP_CALLS or name.startswith(("pytest.", "self.", "unittest.")))


def has_assertion(nodes: list[ast.AST], helpers: set[str]) -> bool:
    return assertion_count(nodes, helpers, stop_at_first=True) > 0


def assertion_count(nodes: list[ast.AST], helpers: set[str], stop_at_first: bool = False) -> int:
    count = 0
    for node in nodes:
        if is_assertion(node, helpers):
            count += 1
            if stop_at_first:
                break
    return count


def is_assertion(node: ast.AST, helpers: set[str]) -> bool:
    """One assert statement or assertion-like call. `with pytest.raises(...)` counts once, through its call."""
    if isinstance(node, ast.Assert):
        return True
    if isinstance(node, ast.Call):
        name = last_name(node.func)
        if isinstance(node.func, ast.Attribute) and isinstance(node.func.value, ast.Call) and dotted(node.func.value.func) == "super":
            return True  # super().test_x(): the parent test does the checking
        return bool(
            name.startswith("assert")
            or name in ASSERT_CONTEXTS
            or name in FAIL_CALLS
            or name in helpers
            or MOCK_ASSERT_RE.match(name)
            or ASSERT_HELPER_RE.match(name)
            or RAISES_WARNS_RE.search(name)
        )
    if isinstance(node, ast.Compare):
        return any(dotted(c).endswith("snapshot") for c in node.comparators)
    return False


def is_weak_assert(node: ast.Assert) -> bool:
    """An assert that checks only existence or type, such as `assert x`, `x is not None`, or `len(x) > 0`."""
    test = node.test
    if isinstance(test, (ast.Name, ast.Attribute)):
        return True
    if isinstance(test, ast.Call) and last_name(test.func) in ("isinstance", "hasattr", "callable", "bool"):
        return True
    if isinstance(test, ast.Compare) and len(test.ops) == 1:
        op, right = test.ops[0], test.comparators[0]
        if isinstance(op, ast.IsNot) and isinstance(right, ast.Constant) and right.value is None:
            return True
        if isinstance(test.left, ast.Call) and last_name(test.left.func) == "len" and isinstance(right, ast.Constant):
            return (isinstance(op, ast.Gt) and right.value == 0) or (isinstance(op, ast.GtE) and right.value == 1) or (isinstance(op, ast.NotEq) and right.value == 0)
    return False


def existence_only(node: ast.AST) -> bool | None:
    """True for an assertion that checks only that something exists; False for any other assertion.

    Stricter than is_weak_assert: a bare `assert user.is_active` is a real check, and so is
    isinstance, which is often the behaviour under test. Only `is not None`, hasattr,
    len(x) > 0, and assertIsNotNone count.
    """
    if isinstance(node, ast.Assert):
        test = node.test
        if isinstance(test, ast.Call) and last_name(test.func) == "hasattr":
            return True
        if isinstance(test, ast.Compare) and len(test.ops) == 1:
            op, right = test.ops[0], test.comparators[0]
            if isinstance(op, ast.IsNot) and isinstance(right, ast.Constant) and right.value is None:
                return True
            if isinstance(test.left, ast.Call) and last_name(test.left.func) == "len" and isinstance(right, ast.Constant):
                return (isinstance(op, ast.Gt) and right.value == 0) or (isinstance(op, ast.GtE) and right.value == 1) or (isinstance(op, ast.NotEq) and right.value == 0)
        return False
    if isinstance(node, ast.Call) and last_name(node.func) == "assertIsNotNone":
        return True
    return False


def is_bare_skip(decorator: ast.AST) -> bool:
    """`@skip` or `@unittest.skip` used without a reason; pytest.mark.skip is a marker and works bare."""
    return not isinstance(decorator, ast.Call) and dotted(decorator) in ("skip", "unittest.skip", "pytest.skip")


def looks_like_message(node: ast.AST) -> bool:
    """A failure message rather than a value to compare: a string, an f-string, % or .format, str(...), or a msg name."""
    if isinstance(node, ast.JoinedStr) or (isinstance(node, ast.Constant) and isinstance(node.value, str)):
        return True
    if isinstance(node, ast.BinOp) and isinstance(node.op, (ast.Mod, ast.Add)):
        return looks_like_message(node.left) or looks_like_message(node.right)
    if isinstance(node, ast.Call):
        if isinstance(node.func, ast.Attribute) and node.func.attr in ("format", "join") and looks_like_message(node.func.value):
            return True
        return last_name(node.func) in ("str", "repr", "format")
    if isinstance(node, (ast.Name, ast.Attribute)):
        name = last_name(node).lower()
        return any(word in name for word in ("msg", "message", "reason", "error", "err", "explain", "detail", "hint"))
    return False


def tautology(node: ast.Assert) -> str | None:
    test = node.test
    if isinstance(test, ast.Constant) and test.value:
        return "asserts a truthy constant"
    if isinstance(test, ast.Tuple) and test.elts:
        return "asserts a non-empty tuple, which is always true"
    if isinstance(test, (ast.List, ast.Set)) and test.elts or isinstance(test, ast.Dict) and test.keys:
        return "asserts a non-empty literal, which is always true"
    return None


def self_comparison(node: ast.Assert) -> bool:
    """x == x is always true for built-in values, but it can be a deliberate test of a custom __eq__."""
    test = node.test
    if isinstance(test, ast.Compare) and len(test.ops) == 1 and isinstance(test.ops[0], (ast.Eq, ast.Is)):
        left, right = test.left, test.comparators[0]
        return ast.dump(left) == ast.dump(right) and not any(isinstance(n, ast.Call) for n in ast.walk(left))
    return False


# --------------------------------------------------------------------------- scanner


class Scanner:
    def __init__(self, config: dict, runner: str, examples: int):
        self.config = config
        self.runner = runner
        self.examples = examples
        self.checks: dict[str, dict] = defaultdict(lambda: {"count": 0, "examples": []})
        self.inventory: dict[str, int] = defaultdict(int)
        self.parse_errors: list[str] = []
        self.defined_tests: list[tuple[str, str]] = []
        self.fixtures: dict[str, list[dict]] = defaultdict(list)
        self.requested: set[str] = set()
        self.exact_bodies: dict[str, list[str]] = defaultdict(list)
        self.literal_bodies: dict[str, list[str]] = defaultdict(list)
        self.tests_per_dir: dict[str, int] = defaultdict(int)
        self.tests_per_file: dict[str, int] = defaultdict(int)
        self.tests_per_class: dict[tuple[str, str], int] = defaultdict(int)
        self.tests: dict[str, dict] = {}
        self.init_classes: set[str] = set()
        self.excluded_dirs: list[Path] = []
        self.testcase_classes: set[str] = set()
        self.transactional_classes: set[str] = set()
        self.called_names: set[str] = set()
        self.misnamed_candidates: list[tuple[str, str, str]] = []
        self.referenced_attrs: set[str] = set()
        self.module_refs: set[str] = set()
        self.disabled_classes: dict[str, str] = {}
        self.base_names: set[str] = set()
        self.module_literals: set[str] = set()
        self.module_containers: set[str] = set()
        self.module_skip_files: set[str] = set()
        self.imported_modules: set[str] = set()
        self.unread_requests: list[tuple[str, str, str]] = []
        self.conftests: list[dict] = []
        self.file_sizes: list[tuple[int, str]] = []
        self.skip_reasons: dict[str, int] = defaultdict(int)

    def add(self, check: str, where: str, detail: str = "") -> None:
        entry = self.checks[check]
        entry["count"] += 1
        if len(entry["examples"]) < self.examples:
            entry["examples"].append(f"{where} – {detail}" if detail else where)

    def is_test_file(self, name: str) -> bool:
        return fnmatch.fnmatch(name, "test*.py") if self.runner == "unittest" else glob_match(name, self.config["python_files"])

    # Files ------------------------------------------------------------------

    def walk(self, roots: list[Path]) -> list[Path]:
        files = set()
        explicit = self.config["norecursedirs"] != DEFAULT_NORECURSE
        for root in roots:
            if root.is_file():
                files.add(root)
                continue
            for dirpath, dirnames, filenames in os.walk(root):
                kept = []
                for d in dirnames:
                    if d in ALWAYS_SKIP_DIRS:
                        continue
                    if glob_match(d, self.config["norecursedirs"]):
                        if explicit and not glob_match(d, DEFAULT_NORECURSE):
                            self.excluded_dirs.append(Path(dirpath) / d)
                        continue
                    kept.append(d)
                dirnames[:] = kept
                files.update(Path(dirpath) / n for n in filenames if n.endswith(".py"))
        return sorted(files)

    def report_excluded_dirs(self, cwd: Path) -> None:
        for directory in self.excluded_dirs:
            count = 0
            for path in directory.rglob("*.py"):
                if self.is_test_file(path.name):
                    try:
                        tree = ast.parse(path.read_text(errors="replace"))
                    except (SyntaxError, ValueError):
                        continue
                    count += sum(1 for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name.startswith("test"))
            if count:
                try:
                    shown = directory.resolve().relative_to(cwd)
                except ValueError:
                    shown = directory
                self.add("in-norecursedirs", str(shown), f"{count} test functions under a directory that norecursedirs excludes, so pytest never collects them")

    def scan_file(self, path: Path, rel: str) -> None:
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
            tree = ast.parse(source, filename=rel)
        except (SyntaxError, ValueError) as exc:
            self.parse_errors.append(f"{rel}: {exc.__class__.__name__}: {exc}")
            return
        lines = source.count("\n") + 1
        is_conftest = path.name == "conftest.py"
        self.collect_requests(tree)
        fixture_nodes = []
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and is_fixture(node):
                fixture_nodes.append((None, node))
            elif isinstance(node, ast.ClassDef):
                fixture_nodes += [(node.name, n) for n in node.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and is_fixture(n)]
        for cls, node in fixture_nodes:
            args = fixture_args(node)
            name = args.get("name") or node.name
            self.fixtures[name].append(
                {"path": rel, "line": node.lineno, "scope": args.get("scope", "function"), "autouse": bool(args.get("autouse")),
                 "conftest": is_conftest, "class": cls, "returns_value": returns_value(node)}
            )
            requested = {a.arg for a in node.args.args + node.args.kwonlyargs} & TRANSACTIONAL_FIXTURES
            if requested:
                self.add(
                    "transactional-tests", f"{rel}:{node.lineno}",
                    f"fixture {name}{' (autouse)' if args.get('autouse') else ''} requests {', '.join(sorted(requested))}, so every test that uses it is transactional",
                )
            # Sleeps and I/O in fixtures cost time in every test that uses them.
            scope = args.get("scope", "function")
            self.check_risks(node, walk_body(node), rel, f"fixture {name} (scope {scope}{', autouse' if args.get('autouse') else ''})", [dotted(d) for d in node.decorator_list])
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and last_name(node.func) in ("register_profile", "load_profile") and "settings" in dotted(node.func):
                self.add("hypothesis-settings", f"{rel}:{node.lineno}", source_of(node))
        if is_conftest:
            self.conftests.append({"path": rel, "lines": lines, "fixtures": len(fixture_nodes)})
            return
        if not self.is_test_file(path.name):
            tests = [n for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name.startswith("test_") and not is_fixture(n)]
            classes = [
                n for n in tree.body
                if isinstance(n, ast.ClassDef) and self.is_unittest_class(n)
                and any(isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef)) and m.name.startswith("test") for m in n.body)
            ]
            in_test_dir = any(part in ("tests", "test", "testing") for part in Path(rel).parent.parts)
            if (tests or classes) and (in_test_dir or "test" in path.name):
                pattern = "test*.py" if self.runner == "unittest" else " ".join(self.config["python_files"])
                self.add("file-not-collected", rel, f"{len(tests)} test functions and {len(classes)} TestCase classes, but the file name does not match {pattern}")
            return
        self.inventory["test_files"] += 1
        self.file_sizes.append((lines, rel))
        self.init_classes = {
            n.name for n in tree.body if isinstance(n, ast.ClassDef) and any(isinstance(m, ast.FunctionDef) and m.name == "__init__" for m in n.body)
        }
        self.module_literals = literal_names(tree.body)
        self.module_containers = container_names(tree.body)
        self.imported_modules = {
            (alias.asname or alias.name.split(".", 1)[0])
            for node in tree.body if isinstance(node, ast.Import) for alias in node.names
        }
        self.check_module_level(tree, rel)
        for node in tree.body:
            if isinstance(node, ast.ImportFrom) and node.module and "test" in node.module.split(".")[-1]:
                imported = [a.asname or a.name for a in node.names if name_match(a.asname or a.name, self.config["python_functions"])]
                if imported and self.runner == "pytest":
                    self.add("imported-test", f"{rel}:{node.lineno}", f"imports {', '.join(imported[:3])} from {node.module}, so pytest collects and runs it here too")
        helpers = {n.name for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and any(isinstance(x, ast.Assert) for x in ast.walk(n))}
        self.module_refs = {n.id for n in ast.walk(tree) if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Load)}
        self.scan_scope(tree.body, rel, "", helpers)

    def collect_requests(self, tree: ast.AST) -> None:
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                self.called_names.add(last_name(node.func))
            elif isinstance(node, ast.Attribute):
                self.referenced_attrs.add(node.attr)
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                self.requested.update(a.arg for a in node.args.args + node.args.kwonlyargs)
            elif isinstance(node, ast.Call) and last_name(node.func) in ("usefixtures", "getfixturevalue", "parametrize"):
                is_param = last_name(node.func) == "parametrize"
                if is_param and not any(kw.arg == "indirect" for kw in node.keywords):
                    continue
                for arg in node.args[:1] if is_param else node.args:
                    if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                        self.requested.update(a.strip() for a in arg.value.split(","))

    def check_module_level(self, tree: ast.Module, rel: str) -> None:
        tests = [n for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and name_match(n.name, self.config["python_functions"])]
        classes = [n for n in tree.body if isinstance(n, ast.ClassDef)]
        for node in tree.body:
            if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "__test__" for t in node.targets):
                if isinstance(node.value, ast.Constant) and node.value.value is False and (tests or classes):
                    self.add("module-disabled", f"{rel}:{node.lineno}", f"the module sets __test__ = False, so pytest collects none of its tests")
            if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "pytestmark" for t in node.targets):
                marks = node.value.elts if isinstance(node.value, (ast.List, ast.Tuple)) else [node.value]
                for mark in marks:
                    if last_name(mark).lower() == "skip":
                        self.add("skip-unconditional", f"{rel}:{node.lineno}", f"module-level pytestmark skips every test in {rel}")
                    self.check_transaction_marker(mark, f"{rel}:{node.lineno}", f"every test in {rel} (pytestmark)")
            if isinstance(node, ast.Expr) and isinstance(node.value, ast.Call) and last_name(node.value.func) == "skip":
                if any(kw.arg == "allow_module_level" for kw in node.value.keywords):
                    self.add("skip-unconditional", f"{rel}:{node.lineno}", f"pytest.skip(allow_module_level=True) skips every test in {rel}")
            value = node.value if isinstance(node, (ast.Expr, ast.Assign)) else None
            if isinstance(value, ast.Call) and last_name(value.func) == "importorskip":
                self.inventory["module_importorskip"] += 1
                self.module_skip_files.add(rel.replace(os.sep, "/"))
            if isinstance(value, ast.Call) and last_name(value.func) == "skip" and any(kw.arg == "allow_module_level" for kw in value.keywords):
                self.module_skip_files.add(rel.replace(os.sep, "/"))
            if isinstance(node, ast.ClassDef):
                for d in node.decorator_list:
                    if is_bare_skip(d):
                        continue  # reported as bare-skip-decorator
                    if last_name(d).lower() == "skip":
                        self.add("skip-unconditional", f"{rel}:{d.lineno}", f"class {node.name} is skipped as a whole")
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and MISNAMED_TEST_RE.match(node.name) and not is_fixture(node):
                if any(isinstance(n, ast.Assert) for n in ast.walk(node)):
                    self.add("misnamed-test", f"{rel}:{node.lineno}", f"{node.name} looks like a misspelt test name, so it never runs")

    def scan_scope(self, body: list[ast.stmt], rel: str, prefix: str, helpers: set[str], unittest_class: bool = False) -> None:
        seen: dict[str, int] = {}
        for node in body:
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and any(is_bare_skip(d) for d in node.decorator_list):
                kind = "class" if isinstance(node, ast.ClassDef) else "test"
                self.add(
                    "bare-skip-decorator", f"{rel}:{node.lineno}",
                    f"{kind} {prefix}{node.name} has @skip without a reason, which replaces it with unittest's inner decorator "
                    "function: its tests never run, and they do not show as skipped",
                )
                continue
            if isinstance(node, ast.ClassDef):
                self.scan_class(node, rel, prefix, helpers, seen)
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not is_fixture(node):
                if self.runner == "unittest" or unittest_class:
                    is_test = bool(prefix) and node.name.startswith("test")
                else:
                    is_test = name_match(node.name, self.config["python_functions"])
                if not is_test:
                    callback = node.name in self.module_refs or any(REGISTRATION_RE.search(dotted(d)) for d in node.decorator_list)
                    if self.runner == "unittest" and not prefix and node.name.startswith("test") and not callback:
                        self.add("not-run-by-runner", f"{rel}:{node.lineno}", f"{node.name} is a module-level function; the unittest runner only runs TestCase methods")
                    continue
                if node.name in seen:
                    self.add("shadowed-test", f"{rel}:{seen[node.name]}", f"{prefix}{node.name} is redefined at line {node.lineno}; the first definition never runs")
                seen[node.name] = node.lineno
                self.scan_test(node, rel, prefix, helpers)

    def scan_class(self, node: ast.ClassDef, rel: str, prefix: str, helpers: set[str], seen: dict[str, int]) -> None:
        unittest_class = self.is_unittest_class(node)
        self.base_names |= {last_name(b) for b in node.bases}
        if self.runner == "unittest":
            collected = unittest_class
            if not collected and name_match(node.name, DEFAULT_CLASSES) and any(
                isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name.startswith("test") for n in node.body
            ):
                self.add("not-run-by-runner", f"{rel}:{node.lineno}", f"class {node.name} has test methods but is not a TestCase subclass, so the unittest runner ignores it")
        else:
            collected = unittest_class or name_match(node.name, self.config["python_classes"])
        if not collected:
            return
        if node.name in seen:
            self.add("shadowed-test", f"{rel}:{seen[node.name]}", f"class {prefix}{node.name} is redefined at line {node.lineno}; the first definition never runs")
        seen[node.name] = node.lineno
        if any(
            isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "__test__" for t in n.targets)
            and isinstance(n.value, ast.Constant) and n.value.value is False
            for n in node.body
        ):
            if any(isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name.startswith("test") for n in node.body):
                self.disabled_classes[node.name] = f"{rel}:{node.lineno}"
            return
        if not unittest_class:
            reason = None
            if any(isinstance(n, ast.FunctionDef) and n.name in ("__init__", "__new__") for n in node.body):
                reason = "defines __init__ or __new__"
            elif any(last_name(d) in DATACLASS_DECORATORS and ("dataclass" in dotted(d) or "attr" in dotted(d)) for d in node.decorator_list):
                reason = "is a dataclass or attrs class, which generates __init__"
            else:
                inherited = [last_name(b) for b in node.bases if last_name(b) in self.init_classes]
                if inherited:
                    reason = f"inherits __init__ from {inherited[0]}"
            if reason:
                self.add("uncollectable-class", f"{rel}:{node.lineno}", f"class {node.name} {reason}, so pytest collects none of its tests")
                return
        bases = {last_name(b) for b in node.bases}
        transactional = bases & (TRANSACTIONAL_BASES | self.transactional_classes)
        own_tests = sum(1 for n in node.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name.startswith("test"))
        if transactional and (bases & TRANSACTIONAL_BASES or own_tests):
            self.add("transactional-tests", f"{rel}:{node.lineno}", f"{node.name} inherits {', '.join(sorted(transactional))} ({own_tests} test methods)")
        for d in node.decorator_list:
            self.check_transaction_marker(d, f"{rel}:{node.lineno}", node.name)
        for n in node.body:
            if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "pytestmark" for t in n.targets):
                for mark in n.value.elts if isinstance(n.value, (ast.List, ast.Tuple)) else [n.value]:
                    self.check_transaction_marker(mark, f"{rel}:{n.lineno}", f"every test in {node.name} (pytestmark)")
        self.inventory["test_classes"] += 1
        class_helpers = helpers | {
            n.name for n in node.body
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
            and any(isinstance(x, ast.Assert) or (isinstance(x, ast.Call) and last_name(x.func).startswith("assert")) for x in ast.walk(n))
        }
        called = {dotted(n.func).rsplit(".", 1)[-1] for n in ast.walk(node) if isinstance(n, ast.Call)}
        for method in node.body:
            if not isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)) or is_fixture(method):
                continue
            name = method.name
            if name.startswith("_") or name in LIFECYCLE_METHODS or name in called:
                continue
            runs = name.startswith("test") if (unittest_class or self.runner == "unittest") else name_match(name, self.config["python_functions"])
            if name.lower().startswith("assert"):
                continue  # assertion helpers such as assertActiveFilter are called by tests elsewhere
            required = len(method.args.args) - len(method.args.defaults) - 1  # beyond self
            if required > 0:
                continue  # callbacks such as hook(self, pages, action) take arguments; tests do not
            if not runs and any(isinstance(n, ast.Assert) or (isinstance(n, ast.Call) and last_name(n.func).startswith("assert")) for n in ast.walk(method)):
                self.misnamed_candidates.append((name, f"{rel}:{method.lineno}", f"{node.name}.{name} checks things but its name does not match the test pattern, and nothing calls it"))
        self.scan_scope(node.body, rel, f"{prefix}{node.name}::", class_helpers, unittest_class=unittest_class)

    def is_unittest_class(self, node: ast.ClassDef) -> bool:
        return any(last_name(b).endswith("TestCase") or last_name(b) in self.testcase_classes for b in node.bases)

    def check_transaction_marker(self, d: ast.AST, where: str, qual: str) -> None:
        if not isinstance(d, ast.Call):
            return
        if dotted(d.func).endswith("django_db"):
            positional = bool(d.args) and isinstance(d.args[0], ast.Constant) and d.args[0].value is True
            flags = sorted(
                kw.arg for kw in d.keywords
                if kw.arg in ("transaction", "reset_sequences") and isinstance(kw.value, ast.Constant) and kw.value.value
            )
            if positional or flags:
                how = "django_db(True)" if positional else f"django_db({', '.join(f'{f}=True' for f in flags)})"
                self.add("transactional-tests", where, f"{qual} uses {how}")
        elif last_name(d.func) == "usefixtures":
            used = {a.value for a in d.args if isinstance(a, ast.Constant) and isinstance(a.value, str)} & TRANSACTIONAL_FIXTURES
            if used:
                self.add("transactional-tests", where, f"{qual} uses the {', '.join(sorted(used))} fixture")

    def scan_test(self, func, rel: str, prefix: str, helpers: set[str]) -> None:
        where = f"{rel}:{func.lineno}"
        qual = f"{prefix}{func.name}"
        nodes = walk_body(func)
        decos = [dotted(d) for d in func.decorator_list]
        self.inventory["test_functions"] += 1
        self.defined_tests.append((rel, qual))
        self.tests_per_dir[str(Path(rel).parent)] += 1
        self.tests_per_file[rel] += 1
        if prefix:
            self.tests_per_class[(rel, prefix.split("::", 1)[0])] += 1
        is_property = any(d.rsplit(".", 1)[-1] == "given" for d in decos)
        if is_property:
            self.inventory["hypothesis_tests"] += 1
        skipped = bool(func.body) and isinstance(func.body[0], ast.Expr) and isinstance(func.body[0].value, ast.Call) and is_skip_call(func.body[0].value)
        placeholder = any(last_name(d).lower() in ("skip", "xfail", "expectedfailure") for d in func.decorator_list)
        if not is_property and not skipped and not placeholder and not has_assertion(nodes, helpers):
            self.add("no-assertion", where, qual)
        for d in func.decorator_list:
            self.check_transaction_marker(d, where, qual)
        params = [a.arg for a in func.args.args + func.args.kwonlyargs if a.arg not in ("self", "cls")]
        requested = set(params) & TRANSACTIONAL_FIXTURES
        if requested:
            self.add("transactional-tests", where, f"{qual} requests {', '.join(sorted(requested))}")
        read = {n.id for n in nodes if isinstance(n, ast.Name)}
        parametrized = {
            name.strip()
            for d in func.decorator_list if isinstance(d, ast.Call) and last_name(d.func) == "parametrize" and d.args
            and isinstance(d.args[0], ast.Constant) and isinstance(d.args[0].value, str)
            for name in d.args[0].value.split(",")
        }
        for param in params:
            if param not in read and param not in parametrized:
                self.unread_requests.append((where, qual, param))
        self.check_asserts(func, nodes, rel, qual)
        checks = [n for n in nodes if is_assertion(n, helpers)]
        last = func.body[-1] if func.body else None
        ends_checking = isinstance(last, ast.Assert) or (isinstance(last, ast.Expr) and is_assertion(last.value, helpers))
        # A test that goes on to call code after its asserts also checks that the calls do not raise.
        if checks and ends_checking and all(existence_only(n) for n in checks):
            self.add("weak-assertions", where, f"{qual} checks only that results exist (is not None, len > 0), so a wrong value passes")
        self.check_cannot_fail(func, rel, where, qual)
        self.check_skips(func, nodes, rel, where, qual)
        self.check_risks(func, nodes, rel, qual, decos)
        self.check_mocks(nodes, where, qual, decos)
        self.check_parametrize(func, where, qual)
        self.check_hypothesis(func, where, qual)
        if not is_property:
            called = {last_name(n.func) for n in nodes if isinstance(n, ast.Call)}
            pair = next(((a, b) for a, b in ROUND_TRIP_PAIRS if a in called and b in called), None)
            if pair is None:
                pair = next(((a, b) for a in sorted(called) if (b := round_trip_partner(a, called))), None)
            if pair:
                self.add("pbt-candidates", where, f"{qual} calls {pair[0]}() and {pair[1]}(): a round-trip property")
        for strip, store in ((False, self.exact_bodies), (True, self.literal_bodies)):
            fp = body_fingerprint(func, strip)
            if fp:
                store[fp].append(f"{where}::{qual}")
        self.tests[f"{rel}::{qual}"] = {
            "line": func.lineno,
            "assertions": assertion_count(nodes, helpers),
            "strong_asserts": sum(1 for n in nodes if isinstance(n, ast.Assert) and not is_weak_assert(n) and not tautology(n))
            + sum(1 for n in nodes if isinstance(n, ast.Call) and last_name(n.func).startswith("assert") and last_name(n.func) not in WEAK_ASSERT_METHODS),
            "skip": placeholder and any(last_name(d).lower() == "skip" for d in func.decorator_list),
            "xfail": any(last_name(d).lower() in ("xfail", "expectedfailure") for d in func.decorator_list),
            "skip_call": skipped,
            "hash": hashlib.sha1("\n".join(ast.dump(st, include_attributes=False) for st in func.body).encode()).hexdigest()[:16],
        }

    def check_asserts(self, func, nodes: list[ast.AST], rel: str, qual: str) -> None:
        for node in nodes:
            if isinstance(node, ast.Assert):
                why = tautology(node)
                if why:
                    self.add("tautology", f"{rel}:{node.lineno}", f"{qual}: {why}")
                elif self_comparison(node):
                    self.add("self-comparison", f"{rel}:{node.lineno}", f"{qual}: compares an expression with itself (a tautology unless it tests a custom __eq__)")
        blocks = [func.body] + [getattr(n, f) for n in nodes for f in ("body", "orelse", "finalbody") if isinstance(getattr(n, f, None), list)]
        for block in blocks:
            stopped = False
            for i, stmt in enumerate(block):
                if not isinstance(stmt, ast.stmt):
                    break
                if isinstance(stmt, ast.Try) and self.unguarded_except_asserts(stmt, block[i + 1] if i + 1 < len(block) else None, nodes):
                    self.add("assert-in-except", f"{rel}:{stmt.lineno}", f"{qual}: the asserts run only when an exception is raised")
                if stopped and any(isinstance(n, ast.Assert) for n in ast.walk(stmt)):
                    self.add("unreachable-assert", f"{rel}:{stmt.lineno}", f"{qual}: assert after a return or raise")
                    break
                if isinstance(stmt, (ast.Return, ast.Raise)):
                    stopped = True

    def check_cannot_fail(self, func, rel: str, where: str, qual: str) -> None:
        own = walk_own(func)
        if any(isinstance(n, (ast.Yield, ast.YieldFrom)) for n in own):
            self.add("yield-in-test", where, f"{qual} contains yield: pytest refuses to collect the module, and by default the whole run stops")
        for n in own:
            if isinstance(n, ast.Return) and n.value is not None and not isinstance(n.value, (ast.Call, ast.Await)) and not (
                isinstance(n.value, ast.Constant) and n.value.value is None
            ):
                self.add("returns-value", f"{rel}:{n.lineno}", f"{qual} returns a value instead of asserting it; pytest passes the test with only a warning")
                break
        for n in own:
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute) and n.func.attr in MOCK_TYPOS:
                self.add("mock-typo", f"{rel}:{n.lineno}", f"{qual} calls .{n.func.attr}(), which checks nothing: the assertion is assert_{n.func.attr}() (Python 3.12+ raises instead)")
        for n in own:
            if isinstance(n, ast.Call) and last_name(n.func) in ("assertTrue", "assertFalse", "failUnless", "failIf") and len(n.args) == 2:
                if not looks_like_message(n.args[1]):
                    self.add("assert-true-two-args", f"{rel}:{n.lineno}", f"{qual}: {last_name(n.func)}(a, b) treats b as the message; assertEqual was probably meant")
        known = self.module_literals | literal_names(own)

        def surely_non_empty(iterable: ast.AST) -> bool:
            return non_empty_literal(iterable, known)

        asserts_total = sum(1 for n in own if isinstance(n, ast.Assert))
        loops = [n for n in own if isinstance(n, (ast.For, ast.AsyncFor))]
        in_loops = sum(1 for n in loops for m in ast.walk(n) if isinstance(m, ast.Assert))
        risky_loop = any(not surely_non_empty(n.iter) for n in loops if any(isinstance(m, ast.Assert) for m in ast.walk(n)))
        if asserts_total and asserts_total == in_loops and risky_loop:
            self.add("assert-only-in-loop", where, f"{qual}: every assert is inside a loop, so the test checks nothing when the loop is empty")
        for d in func.decorator_list:
            if isinstance(d, ast.Call) and dotted(d.func).endswith("parametrize") and len(d.args) >= 2:
                values = d.args[1]
                if isinstance(values, (ast.List, ast.Tuple)) and not values.elts:
                    self.add("empty-parametrize", where, f"{qual} is parametrised with an empty list, so pytest skips it silently")

    @staticmethod
    def unguarded_except_asserts(node: ast.Try, following: ast.stmt | None, nodes: list[ast.AST]) -> bool:
        """True when a try's handlers assert, but nothing fails the test if no exception is raised."""

        def checks(stmts) -> bool:
            return any(
                isinstance(n, (ast.Assert, ast.Raise)) or (isinstance(n, ast.Call) and last_name(n.func) in FAIL_CALLS)
                for s in stmts
                for n in ast.walk(s)
            )

        def fails(stmts) -> bool:
            return any(
                isinstance(n, ast.Raise) or (isinstance(n, ast.Call) and last_name(n.func) in FAIL_CALLS)
                or (isinstance(n, ast.Assert) and isinstance(n.test, ast.Constant) and not n.test.value)
                for s in stmts
                for n in ast.walk(s)
            )

        # A handler with only `assert False` means "fail if this raises", which is fine.
        in_handler = any(isinstance(n, ast.Assert) and not isinstance(n.test, ast.Constant) for h in node.handlers for n in ast.walk(h))
        if not in_handler or any(isinstance(n, ast.Assert) for s in node.body for n in ast.walk(s)):
            return False
        if checks(node.orelse) or fails(node.body) or (following is not None and fails([following])):
            return False
        handled = {last_name(h.type) for h in node.handlers if h.type is not None}
        return not any(
            isinstance(n, ast.Call) and RAISES_WARNS_RE.search(last_name(n.func)) and n.args and last_name(n.args[0]) in handled
            for n in nodes
        )

    def check_skips(self, func, nodes: list[ast.AST], rel: str, where: str, qual: str) -> None:
        for d in func.decorator_list:
            name = last_name(d).lower()
            if name not in ("skip", "skipif", "xfail", "skipunless", "expectedfailure"):
                continue
            kind = {"skipunless": "skipif", "expectedfailure": "xfail"}.get(name, name)
            reason, strict = "", None
            if isinstance(d, ast.Call):
                for kw in d.keywords:
                    if kw.arg == "reason" and isinstance(kw.value, ast.Constant):
                        reason = str(kw.value.value)
                    elif kw.arg == "strict" and isinstance(kw.value, ast.Constant):
                        strict = bool(kw.value.value)
                if not reason and d.args and isinstance(d.args[-1], ast.Constant) and isinstance(d.args[-1].value, str):
                    reason = d.args[-1].value
            self.inventory[f"marked_{kind}"] += 1
            self.skip_reasons[(reason[:60] or "(no reason)")] += 1
            detail = f"{qual}{': ' + reason[:80] if reason else ''}"
            where = f"{rel}:{d.lineno}"
            if kind == "skip":
                self.add("skip-unconditional", where, detail)
            if kind == "xfail" and isinstance(d, ast.Call) and any(kw.arg == "run" and isinstance(kw.value, ast.Constant) and kw.value.value is False for kw in d.keywords):
                self.add("xfail-never-runs", where, f"{detail} (run=False: the test body never runs)")
            elif kind == "xfail" and "mark.xfail" in dotted(d) and strict is not True and not self.config["xfail_strict"]:
                # Only pytest's own marker: custom XFAIL decorators may already fail on an unexpected pass.
                self.add("xfail-not-strict", where, detail)
        for stmt in func.body:
            if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Call) and is_skip_call(stmt.value):
                self.add("skip-inside-test", f"{rel}:{stmt.lineno}", f"{qual} calls {dotted(stmt.value.func)} unconditionally")
        self.inventory["conditional_skip_calls"] += sum(
            1 for node in nodes if isinstance(node, ast.Call) and is_skip_call(node)
        ) - sum(1 for stmt in func.body if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Call) and is_skip_call(stmt.value))

    def check_risks(self, func, nodes: list[ast.AST], rel: str, qual: str, decos: list[str]) -> None:
        frozen = any(any(f in d for f in FREEZE_NAMES) for d in decos)
        frozen = frozen or bool({a.arg for a in func.args.args} & FREEZE_NAMES)
        frozen = frozen or any(isinstance(n, ast.Name) and n.id in FREEZE_NAMES for n in nodes)
        for node in nodes:
            if isinstance(node, ast.Call):
                name = dotted(node.func)
                for check, targets in RISK_CALLS.items():
                    if not call_matches(name, targets):
                        continue
                    if check == "risk-clock" and frozen:
                        continue
                    detail = qual
                    if check == "risk-sleep":
                        arg = node.args[0] if node.args else None
                        if isinstance(arg, ast.Constant) and isinstance(arg.value, (int, float)):
                            if arg.value <= 0:
                                continue
                            detail = f"{qual} sleeps {arg.value}s"
                    self.add(check, f"{rel}:{node.lineno}", detail)
            elif isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Subscript) and dotted(target.value) == "os.environ":
                        self.add("risk-env-mutation", f"{rel}:{node.lineno}", f"{qual} writes os.environ directly instead of using monkeypatch")
            elif isinstance(node, ast.Global):
                self.add("risk-global-state", f"{rel}:{node.lineno}", f"{qual} declares global {', '.join(node.names)}")
        self.check_shared_writes(func, nodes, rel, qual)

    def check_shared_writes(self, func, nodes: list[ast.AST], rel: str, qual: str) -> None:
        """Writes that outlive the test: module-level containers, and imported modules' attributes."""
        declared_global = {name for n in nodes if isinstance(n, ast.Global) for name in n.names}
        local = {n.id for n in nodes if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Store)} - declared_global
        local |= {a.arg for a in func.args.args + func.args.kwonlyargs}

        def shared(expr: ast.AST) -> str | None:
            if isinstance(expr, ast.Name) and expr.id in self.module_containers and expr.id not in local:
                return expr.id
            if isinstance(expr, ast.Attribute) and isinstance(expr.value, ast.Name):
                module = expr.value.id
                if module in self.imported_modules and module not in local and expr.attr.isupper():
                    return f"{module}.{expr.attr}"
            return None

        seen: set[str] = set()
        for node in nodes:
            targets = node.targets if isinstance(node, (ast.Assign, ast.Delete)) else [node.target] if isinstance(node, (ast.AugAssign, ast.AnnAssign)) else []
            found = None
            for target in targets:
                if isinstance(target, ast.Subscript):
                    found = shared(target.value)
                elif isinstance(target, ast.Attribute) and isinstance(target.value, ast.Name):
                    module = target.value.id
                    if module in self.imported_modules and module not in local and not isinstance(node, ast.Delete):
                        found = f"{module}.{target.attr} (set without monkeypatch)"
                if found:
                    break
            if found is None and isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr in MUTATING_METHODS:
                found = shared(node.func.value)
            if found and found not in seen:
                seen.add(found)
                self.add("risk-global-state", f"{rel}:{node.lineno}", f"{qual} changes module-level {found}, which outlives the test")

    def check_mocks(self, nodes: list[ast.AST], where: str, qual: str, decos: list[str]) -> None:
        def is_patch(name: str) -> bool:
            return "patch" in name.split(".") or name.endswith(("patch.object", "patch.dict", "patch.multiple"))

        patches = sum(1 for d in decos if is_patch(d))
        for node in nodes:
            if isinstance(node, ast.Call):
                name = dotted(node.func)
                if is_patch(name):
                    patches += 1
                elif last_name(node.func) in ("Mock", "MagicMock", "AsyncMock", "NonCallableMock") and not node.args and not any(
                    kw.arg in ("spec", "spec_set") for kw in node.keywords
                ):
                    self.inventory["mocks_without_spec"] += 1
        if patches >= 5:
            self.add("mock-density", where, f"{qual} patches {patches} targets")

    def check_parametrize(self, func, where: str, qual: str) -> None:
        product, stacked = 1, 0
        for d in func.decorator_list:
            if isinstance(d, ast.Call) and dotted(d.func).endswith("parametrize") and len(d.args) >= 2:
                values = d.args[1]
                if isinstance(values, (ast.List, ast.Tuple)):
                    product *= max(1, len(values.elts))
                    stacked += 1
        if stacked:
            self.inventory["parametrized_tests"] += 1
            self.inventory["parametrize_cases_estimate"] += product
        if product >= 50:
            self.add("parametrize-size", where, f"{qual}: about {product} cases from {stacked} parametrize decorator(s)")

    def check_hypothesis(self, func, where: str, qual: str) -> None:
        for d in func.decorator_list:
            if isinstance(d, ast.Call) and last_name(d.func) == "settings":
                for kw in d.keywords:
                    if kw.arg in ("max_examples", "deadline", "suppress_health_check", "derandomize", "phases"):
                        self.add("hypothesis-settings", where, f"{qual}: {kw.arg}={source_of(kw.value)}")

    # Finishing ---------------------------------------------------------------

    def finish(self, nodeids: str | None) -> None:
        exact_groups = [ms for ms in self.exact_bodies.values() if len(ms) >= 2]
        exact_members = {m for ms in exact_groups for m in ms}
        for members in sorted(exact_groups, key=len, reverse=True):
            by_file: dict[str, list[str]] = defaultdict(list)
            for m in members:
                by_file[m.split(":", 1)[0]].append(m)
            for same_file in by_file.values():
                names = {m.rsplit("::", 1)[-1] for m in same_file}
                if len(same_file) >= 2 and len(names) >= 2:
                    shown = ", ".join(sorted(names)[:4])
                    self.add("exact-duplicate-body", same_file[0].split("::", 1)[0], f"{len(same_file)} tests in one file with identical bodies: {shown}")
            if len(by_file) >= 2:
                shown = ", ".join(f"{p}::{by_file[p][0].rsplit('::', 1)[-1]}" for p in list(by_file)[:3])
                self.add("cross-file-duplicate-body", members[0].split("::", 1)[0], f"identical bodies in {len(by_file)} files (imports or fixtures may differ): {shown}")
        for members in sorted(self.literal_bodies.values(), key=len, reverse=True):
            if len(members) >= 3 and not set(members) <= exact_members:
                names = ", ".join(m.rsplit("::", 1)[-1] for m in members[:4])
                self.add("literal-only-body", members[0].split("::", 1)[0], f"{len(members)} tests differ only in literals: {names}")

        collected_ids: list[str] = []
        if nodeids:
            collected_ids = [
                line.strip() for line in Path(nodeids).read_text(errors="replace").splitlines()
                if "::" in line and not line.strip().startswith(("=", "<"))
            ]
        for name, defs in sorted(self.fixtures.items()):
            for f in defs:
                if not f["autouse"]:
                    continue
                if collected_ids:
                    # Collected IDs count parametrised cases, which is what the fixture really reaches.
                    path = f["path"].replace(os.sep, "/")
                    base = str(Path(f["path"]).parent).replace(os.sep, "/")
                    if f["class"]:
                        reach = sum(1 for n in collected_ids if n.startswith(f"{path}::{f['class']}::"))
                    elif f["conftest"]:
                        reach = sum(1 for n in collected_ids if base in ("", ".") or n.startswith(base + "/"))
                    else:
                        reach = sum(1 for n in collected_ids if n.startswith(path + "::"))
                    self.add("autouse-fixtures", f"{f['path']}:{f['line']}", f"{name} (scope {f['scope']}) reaches {reach} collected tests")
                    continue
                if f["class"]:
                    reach = self.tests_per_class.get((f["path"], f["class"]), 0)
                elif f["conftest"]:
                    base = str(Path(f["path"]).parent)
                    reach = sum(n for d, n in self.tests_per_dir.items() if base in ("", ".") or d == base or d.startswith(base + os.sep))
                else:
                    reach = self.tests_per_file.get(f["path"], 0)
                self.add("autouse-fixtures", f"{f['path']}:{f['line']}", f"{name} (scope {f['scope']}) reaches about {reach} tests")
            if name not in self.requested and name not in PLUGIN_FIXTURES and not any(f["autouse"] for f in defs):
                self.add("unused-fixtures", f"{defs[0]['path']}:{defs[0]['line']}", f"{name} is never requested by name")

        for where, qual, param in self.unread_requests:
            defs = self.fixtures.get(param)
            if defs and any(f["returns_value"] for f in defs) and not any(f["autouse"] for f in defs):
                self.add(
                    "unread-fixture", where,
                    f"{qual} requests {param}, which returns a value, and never reads it; "
                    "if only its side effects matter, @pytest.mark.usefixtures says so, otherwise its setup is wasted",
                )
        for name, where, detail in self.misnamed_candidates:
            if name not in self.called_names and name not in self.referenced_attrs:
                self.add("misnamed-test", where, detail)
        for name, where in sorted(self.disabled_classes.items()):
            if name not in self.base_names:
                self.add("disabled-class", where, f"class {name} sets __test__ = False and no scanned class inherits from it, so its tests never run")
        if nodeids:
            collected = set()
            for line in Path(nodeids).read_text(errors="replace").splitlines():
                line = line.strip()
                if "::" in line and not line.startswith(("=", "<")):
                    collected.add(line.split("[", 1)[0])
            by_file: dict[str, list[str]] = defaultdict(list)
            for nodeid in collected:
                by_file[nodeid.split("::", 1)[0]].append(nodeid)

            def explained(rel: str, qual: str) -> bool:
                """Defined tests that run under another ID, or that the scan explains another way."""
                path = rel.replace(os.sep, "/")
                if "::" in qual and qual.split("::", 1)[0] in self.base_names:
                    return True  # a base class's tests run under its subclasses' IDs
                if path in self.module_skip_files:
                    return True  # the module skips itself, for example importorskip of a missing package
                prefix = f"{path}::{qual}_"  # parameterized.expand and ddt append _0, _1_name, ...
                return any(nodeid.startswith(prefix) for nodeid in by_file.get(path, ()))

            missing = [
                (rel, qual) for rel, qual in self.defined_tests
                if f"{rel}::{qual}".replace(os.sep, "/") not in collected and not explained(rel, qual)
            ]
            if collected and self.defined_tests and len(missing) > 0.5 * len(self.defined_tests):
                self.add(
                    "not-collected-check-skipped", nodeids,
                    f"{len(missing)} of {len(self.defined_tests)} defined tests are missing from the node IDs; paths probably do not match (run from the pytest rootdir)",
                )
            else:
                for rel, qual in missing:
                    self.add("not-collected", rel, qual)


CLASS_HEADER_RE = re.compile(r"^[ \t]*class[ \t]+(\w+)[ \t]*\(([^)]*)\)", re.M)


def class_bases(files: list[Path]) -> dict[str, set[str]]:
    """Base class names for every class header in the scanned files (a fast regex pre-pass)."""
    bases_of: dict[str, set[str]] = defaultdict(set)
    for path in files:
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for name, bases in CLASS_HEADER_RE.findall(text):
            bases_of[name] |= {b.strip().split("[", 1)[0].rsplit(".", 1)[-1] for b in bases.split(",") if b.strip() and "=" not in b}
    return bases_of


def inheritors(bases_of: dict[str, set[str]], is_root) -> set[str]:
    """Names of classes that inherit a root base, directly or through other scanned classes."""
    known = {name for name, bases in bases_of.items() if any(is_root(b) for b in bases)}
    changed = True
    while changed:
        changed = False
        for name, bases in bases_of.items():
            if name not in known and bases & known:
                known.add(name)
                changed = True
    return known


def blame_dates(examples: list[str]) -> list[str]:
    dated = []
    for ex in examples:
        location = ex.split(" – ", 1)[0]
        path, _, line = location.rpartition(":")
        if not path or not line.isdigit():
            dated.append(ex)
            continue
        try:
            out = subprocess.run(
                ["git", "blame", "-w", "-C", "--porcelain", "-L", f"{line},{line}", "--", path],
                capture_output=True, text=True, timeout=30, check=False,
            ).stdout
        except (OSError, subprocess.TimeoutExpired):
            dated.append(ex)
            continue
        m = re.search(r"^author-time (\d+)", out, re.M)
        dated.append(f"{ex} (line last changed {_dt.date.fromtimestamp(int(m.group(1))).isoformat()})" if m else ex)
    return dated


NARROWING_KEYS = ("python_files", "python_classes", "python_functions", "testpaths", "norecursedirs", "xfail_strict", "filterwarnings")
# addopts additions that run fewer tests or hide failures.
NARROWING_OPTIONS = {"--deselect", "--ignore", "--ignore-glob", "-m", "-k", "--lf", "--last-failed", "--sw", "--stepwise", "-x", "--exitfirst", "--maxfail", "-p", "--reruns", "--runxfail", "--continue-on-collection-errors"}


def tamper_diff(before: dict, after: dict) -> dict:
    """Compare two scans: removed tests, new skips and xfails, lost assertions, and discovery changes."""
    b, a = before.get("tests", {}), after.get("tests", {})
    removed = sorted(set(b) - set(a))
    added = sorted(set(a) - set(b))
    added_by_hash = {a[t]["hash"]: t for t in added}
    moved = {t: added_by_hash[b[t]["hash"]] for t in removed if b[t]["hash"] in added_by_hash}
    removed = [t for t in removed if t not in moved]
    added = [t for t in added if t not in set(moved.values())]
    common = sorted(set(b) & set(a)) + [t for t in moved]
    after_of = {t: a[moved.get(t, t)] for t in common}
    newly_skipped = [t for t in common if not (b[t]["skip"] or b[t]["skip_call"]) and (after_of[t]["skip"] or after_of[t]["skip_call"])]
    newly_xfail = [t for t in common if not b[t]["xfail"] and after_of[t]["xfail"]]
    fewer_asserts = [
        {"test": t, "before": b[t]["assertions"], "after": after_of[t]["assertions"]}
        for t in common
        if after_of[t]["assertions"] < b[t]["assertions"]
    ]
    weaker_asserts = [
        {"test": t, "strong_before": b[t].get("strong_asserts", 0), "strong_after": after_of[t].get("strong_asserts", 0)}
        for t in common
        if after_of[t].get("strong_asserts", 0) < b[t].get("strong_asserts", 0) and after_of[t]["assertions"] >= b[t]["assertions"]
    ]
    config = {
        k: {"before": before.get("config", {}).get(k), "after": after.get("config", {}).get(k)}
        for k in NARROWING_KEYS
        if before.get("config", {}).get(k) != after.get("config", {}).get(k)
    }
    narrowing = []
    before_opts, after_opts = before.get("config", {}).get("addopts", []), after.get("config", {}).get("addopts", [])
    for token in after_opts:
        if token not in before_opts and token.split("=", 1)[0] in NARROWING_OPTIONS:
            narrowing.append(token)
    weakened = bool(removed or newly_skipped or newly_xfail or fewer_asserts or weaker_asserts or config or narrowing)
    return {
        "removed": removed,
        "added": added,
        "moved": moved,
        "newly_skipped": newly_skipped,
        "newly_xfail": newly_xfail,
        "fewer_assertions": fewer_asserts,
        "weaker_assertions": weaker_asserts,
        "discovery_config_changed": config,
        "narrowing_addopts": narrowing,
        "weakened": weakened,
    }


def cmd_diff(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="static_scan.py diff", description="Tamper check: compare two scans taken before and after a change.")
    parser.add_argument("before", help="--json-out of a scan before the change")
    parser.add_argument("after", help="--json-out of a scan after the change")
    parser.add_argument("--json-out")
    args = parser.parse_args(argv)
    result = tamper_diff(json.loads(Path(args.before).read_text()), json.loads(Path(args.after).read_text()))
    print(
        f"tests removed: {len(result['removed'])}   added: {len(result['added'])}   moved or renamed: {len(result['moved'])}   "
        f"newly skipped: {len(result['newly_skipped'])}   newly xfail: {len(result['newly_xfail'])}   fewer assertions: {len(result['fewer_assertions'])}   "
        f"weaker assertions: {len(result['weaker_assertions'])}"
    )
    for t in result["removed"][:8]:
        print(f"  removed: {t}")
    for t in (result["newly_skipped"] + result["newly_xfail"])[:8]:
        print(f"  now skipped or xfail: {t}")
    for row in result["fewer_assertions"][:8]:
        print(f"  assertions {row['before']} -> {row['after']}: {row['test']}")
    for row in result["weaker_assertions"][:8]:
        print(f"  strong assertions {row['strong_before']} -> {row['strong_after']} (a check became 'is not None', truthiness, or similar): {row['test']}")
    for token in result["narrowing_addopts"]:
        print(f"  addopts gained {token!r}, which runs fewer tests or hides failures")
    for key, change in result["discovery_config_changed"].items():
        print(f"  discovery setting {key}: {change['before']} -> {change['after']}")
    print("verdict: " + ("WEAKENED – every item above needs the user's explicit approval" if result["weakened"] else "no weakening found"))
    if args.json_out:
        write_out(args.json_out, json.dumps(result, indent=2))
        print(f"json: {args.json_out}")
    return 1 if result["weakened"] else 0


def write_out(path_text: str, text: str) -> None:
    path = Path(path_text)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv[:1] == ["diff"]:
        return cmd_diff(argv[1:])
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("paths", nargs="*", help="test directories or files (default: testpaths, or .)")
    parser.add_argument("--config", default=".", help="directory holding the pytest configuration (default: .)")
    parser.add_argument("--runner", choices=("pytest", "unittest"), default="pytest", help="discovery rules to apply")
    parser.add_argument("--nodeids", help="output of `pytest --collect-only -q`, to find tests that are never collected")
    parser.add_argument("--blame", action="store_true", help="add the last-change date to skip and xfail examples")
    parser.add_argument("--examples", type=int, default=3, help="examples to keep per check (default 3)")
    parser.add_argument("--json-out", help="write the full result as JSON")
    args = parser.parse_args(argv)

    config_dir = Path(args.config).resolve()
    config = read_pytest_config(config_dir)
    roots = [Path(p) for p in args.paths] or [config_dir / p for p in config["testpaths"]]
    roots = [r for r in roots if r.exists()] or [config_dir]
    scanner = Scanner(config, args.runner, args.examples)
    files = scanner.walk(roots)
    bases_of = class_bases(files)
    scanner.testcase_classes = inheritors(bases_of, lambda b: b.endswith("TestCase"))
    scanner.transactional_classes = inheritors(bases_of, lambda b: b in TRANSACTIONAL_BASES)
    cwd = Path.cwd().resolve()
    for path in files:
        try:
            rel = str(path.resolve().relative_to(cwd))
        except ValueError:
            rel = str(path)
        scanner.scan_file(path, rel)
    scanner.finish(args.nodeids)
    scanner.report_excluded_dirs(cwd)
    if args.blame:
        for check in ("skip-unconditional", "xfail-not-strict"):
            if check in scanner.checks:
                scanner.checks[check]["examples"] = blame_dates(scanner.checks[check]["examples"])

    inv = dict(scanner.inventory)
    result = {
        "config": config,
        "runner": args.runner,
        "roots": [str(r) for r in roots],
        "files_scanned": len(files),
        "parse_errors": scanner.parse_errors,
        "inventory": inv,
        "largest_test_files": [{"path": p, "lines": n} for n, p in sorted(scanner.file_sizes, reverse=True)[:10]],
        "conftest_files": sorted(scanner.conftests, key=lambda c: -c["lines"]),
        "fixtures_defined": sum(len(v) for v in scanner.fixtures.values()),
        "top_skip_reasons": sorted(scanner.skip_reasons.items(), key=lambda kv: -kv[1])[:10],
        "checks": {k: v for k, v in sorted(scanner.checks.items()) if v["count"]},
        "tests": scanner.tests,
        "caveat": "Static counts are estimates. Confirm each candidate by reading the code or running it before you report it.",
    }
    print(f"config: {config['source'] or 'none found (pytest defaults)'}   runner rules: {args.runner}")
    print(
        f"scanned {len(files)} files: {inv.get('test_files', 0)} test files, {inv.get('test_functions', 0)} test functions "
        f"(static estimate), {inv.get('test_classes', 0)} classes, {result['fixtures_defined']} fixtures, {len(scanner.conftests)} conftest files"
    )
    if inv.get("parametrized_tests"):
        print(f"parametrised tests: {inv['parametrized_tests']}, expanding to about {inv['parametrize_cases_estimate']} cases")
    if inv.get("hypothesis_tests"):
        print(f"property-based tests (@given): {inv['hypothesis_tests']}")
    if scanner.parse_errors:
        print(f"parse errors: {len(scanner.parse_errors)} (try the project's Python), for example {scanner.parse_errors[0][:120]}")
    for name, entry in sorted(result["checks"].items(), key=lambda kv: -kv[1]["count"])[:24]:
        print(f"{name}: {entry['count']}")
        for ex in entry["examples"][:2]:
            print(f"    {ex[:170]}")
    if args.json_out:
        write_out(args.json_out, json.dumps(result, indent=2))
        print(f"json: {args.json_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
